<?php
 
/************************************************************** 
 * XML files working directories.
 **************************************************************/
 $xml_files_dir = "directories/xml_files/"; // Current files to be processed
 $processed_dir = "directories/processed/"; // Files that aleady been processed
 $failed_dir    = "directories/failed/";  // Files failed to process.

 /**************************************************************     
  * Property Items and Items Fields
  * Source: http://ask.realestate.com.au/reaxml/propertylistdtd/
  **************************************************************/
 
 // Features Array List
 $features = array(
     'bedrooms',
    'bathrooms',
    'ensuite',
    'garages',
    'carports',
    'remoteGarage',
    'secureParking',
    'airConditioning',
    'alarmSystem',
    'vacuumSystem',
    'intercom',
    'pool',
    'poolInGround',
    'poolAboveGround',
    'spa',
    'tennisCourt',
    'balcony',
    'deck',
    'courtyard',
    'outdoorEnt',
    'shed',
    'fullyFenced',
    'openFirePlace',
    'openSpaces',
    'toilets',
    'livingAreas',
    'heating',
    'hotWaterService'=>array("attributecustom", "type"),
    'insideSpa',
    'outsideSpa',
    'broadband',
    'builtInRobes',
    'dishwasher',
    'ductedCooling',
    'ductedHeating',
    'evaporativeCooling',
    'floorboards',
    'gasHeating',
    'gym',
    'hydronicHeating',
    'payTV',
    'reverseCycleAirCon',
    'rumpusRoom',
    'splitSystemAirCon',
    'splitSystemHeating',
    'study',
    'workshop',
    'otherFeatures');

// Property Type: Business fields
 $business_fields = array(
    'agentID',
    'uniqueID',
    'marketing',
    'exclusivity',
    'commercialListingType',
    'underOffer',
    'listingAgent',
    'franchise',
    'price',
    'priceView',
    'businessLease' => array("attributecustom"=>"period"),
    'takings',
    'return',
    'currentLeaseEndDate',
    'furtherOptions',
    'municipality',
    'streetDirectory',
    'businessCategory' => array("attributecustom"=>"id"),
    'headline',
    'description',
    'terms',
    'soldDetails' => array("price", "date"),
    'buildingDetails' => array('area', 'energyRating'),
    'vendorDetails',
    'externalLink',
    'extraFields',
    'images',
    'objects',
    'miniweb',
    'purchaseOrder',
    'address' => array(
        'site',
        'subNumber',
        'lotNumber',
        'streetNumber',
        'street',
        'suburb',
        'state',
        'postcode',
        'region',
        'country',
    ),
    'status',
);

 // Property Type: Residentials fields
 $residential_fields = array('agentID',
    'uniqueID',
    'authority',
    'underOffer',
    'isHomeLandPackage',
    'listingAgent',
    'price',
    'priceView',
    'municipality',
    'streetDirectory',
    'category' => array("attributecustom"=>"name"),
    'headline',
    'description',
    'features' => $features,
    'soldDetails' => array("price", "date"),
    'landDetails' => array("area", "frontage", "depth", "crossOver"),
    'buildingDetails' => array('area', 'energyRating'),
    'inspectionTimes',
    'auction' =>  array("attributecustom"=>"date"),
    'vendorDetails',
    'externalLink',
    'videoLink',
    'extraFields',
    'images',
    'newConstruction',
    'ecoFriendly',
    'idealFor',
    'views',
    'objects',
   'address' => array(
        'site',
        'subNumber',
        'lotNumber',
        'streetNumber',
        'street',
        'suburb',
        'state',
        'postcode',
        'region',
        'country',
    ),
    'status',
);

 // Property Type: Rental fields
 $rental_fields = array(
    'agentID',
    'uniqueID',
    'listingAgent',
    'dateAvailable',
    'rent',
    'priceView',
    'bond',
    'municipality',
    'streetDirectory',
    'category',
    'headline',
    'description',
    'features' => $features,
    'holiday',
    'landDetails',
    'newConstruction',
    'buildingDetails',
    'inspectionTimes',
    'externalLink',
    'videoLink',
    'extraFields',
    'images',
    'objects',
    'ecoFriendly',
    'views',
    'allowances',
    'address' => array(
        'site',
        'subNumber',
        'lotNumber',
        'streetNumber',
        'street',
        'suburb',
        'state',
        'postcode',
        'region',
        'country',
    ),
    'status',
);
 
 // Property Type: holidayRental  fields
 $holidayRental_fields = array(
    'agentID',
    'uniqueID',
    'listingAgent',
    'dateAvailable',
    'rent' => array("attributecustom"=>"period"),
    'priceView',
    'bond',
    'municipality',
    'streetDirectory',
    'holidayCategory' => array("attributecustom"=>"name"),
    'headline',
    'description',
    'features' => $features,
    'landDetails' => array("area", "frontage", "depth", "crossOver"),
    'buildingDetails',
    'inspectionTimes',
    'externalLink',
    'availabilityLink',
    'extraFields',
    'images',
    'objects',
    'address' => array(
        'site',
        'subNumber',
        'lotNumber',
        'streetNumber',
        'street',
        'suburb',
        'state',
        'postcode',
        'region',
        'country',
    ),
    'status',
);

// Property Type: Rural  fields
 $rural_fields = array(
    'agentID',
    'uniqueID',
    'authority' ,
    'underOffer',
    'listingAgent',
    'price',
    'priceView',
    'address',
    'municipality',
    'streetDirectory',
    'ruralCategory'=>array("attributecustom"=>"name"),
    'headline',
    'description',
    'features' => $features,
    'ruralFeatures',
    'soldDetails' => array("price", "date"),
    'landDetails',
    'buildingDetails',
    'inspectionTimes',
    'auction' => array("attributecustom"=>"date"),
    'vendorDetails',
    'externalLink',
    'videoLink',
    'extraFields',
    'images',
    'ecoFriendly',
    'idealFor',
    'views',
    'objects',
    'address' => array(
        'site',
        'subNumber',
        'lotNumber',
        'streetNumber',
        'street',
        'suburb',
        'state',
        'postcode',
        'region',
        'country',
    ),
    'status',
);
 
 // Property Type: Commercial  fields
 $commercial_fields = array(
     'agentID',
    'uniqueID',
    'marketing',
    'commercialAuthority',
    'exclusivity',
    'commercialListingType',
    'underOffer',
    'listingAgent',
    'price',
    'priceView',
    'commercialRent' => array("attributecustom"=>"period"),
    'outgoings',
    'return',
    'currentLeaseEndDate',
    'tenancy',
    'furtherOptions',
    'isMultiple',
    'municipality',
    'streetDirectory',
    'commercialCategory',
    'headline',
    'description',
    'highlight',
    'soldDetails'=> array("price", "date"),
    'landDetails',
    'buildingDetails' => array('area', 'energyRating'),
    'propertyExtent',
    'carSpaces',
    'parkingComments',
    'auction' => array("attributecustom"=>"date"),
    'vendorDetails',
    'zone',
    'externalLink',
    'videoLink',
    'extraFields',
    'images',
    'objects',
    'miniweb',
    'purchaseOrder',
    'address' => array(
        'site',
        'subNumber',
        'lotNumber',
        'streetNumber',
        'street',
        'suburb',
        'state',
        'postcode',
        'region',
        'country',
    ),
    'status',
);
 
 // Property Type: Commercial Land Property
 $commercialLand_fields = array
    ('agentID',
    'uniqueID',
    'marketing',
    'authority',
    'commercialListingType',
    'underOffer',
    'listingAgent',
    'price',
    'priceView',
    'commercialRent',
    'outgoings',
    'return',
    'currentLeaseEndDate',
    'address' => array(
        'site',
        'subNumber',
        'lotNumber',
        'streetNumber',
        'street',
        'suburb',
        'state',
        'postcode',
        'region',
        'country',
    ),
    'municipality',
    'estate',
    'streetDirectory',
    'headline',
    'description',
    'highlight',
    'soldDetails' => array("price", "date"),
    'landDetails',
    'auction' => array("attributecustom"=>"date"),
    'vendorDetails',
    'externalLink',
    'videoLink',
    'extraFields',
    'images',
    'objects',
    'miniweb',
    'purchaseOrder',
    'status');
